#!/bin/sh
# Ambiguous emoji: text presentation (bare) vs emoji presentation (with U+FE0F)
# These characters have East Asian Width "Ambiguous" and should stay in one cell.
printf "Ambiguous emoji — text vs emoji presentation:\r\n"
printf "\r\n"
printf "  Bare    FE0F    Name\r\n"
printf "  ⚠  vs  ⚠️   Warning sign\r\n"
printf "  ☀  vs  ☀️   Sun\r\n"
printf "  ☁  vs  ☁️   Cloud\r\n"
printf "  ☂  vs  ☂️   Umbrella\r\n"
printf "  ☃  vs  ☃️   Snowman\r\n"
printf "  ☄  vs  ☄️   Comet\r\n"
printf "  ☎  vs  ☎️   Telephone\r\n"
printf "  ☘  vs  ☘️   Shamrock\r\n"
printf "  ☠  vs  ☠️   Skull and crossbones\r\n"
printf "  ☢  vs  ☢️   Radioactive\r\n"
printf "  ☣  vs  ☣️   Biohazard\r\n"
printf "  ☮  vs  ☮️   Peace\r\n"
printf "  ☯  vs  ☯️   Yin yang\r\n"
printf "  ♈  vs  ♈️   Aries\r\n"
printf "  ♻  vs  ♻️   Recycling\r\n"
printf "  ⚡  vs  ⚡️   High voltage\r\n"
printf "  ⚽  vs  ⚽️   Soccer ball\r\n"
printf "  ⚾  vs  ⚾️   Baseball\r\n"
printf "  ⛄  vs  ⛄️   Snowman without snow\r\n"
printf "  ⛅  vs  ⛅️   Sun behind cloud\r\n"
printf "  ⛎  vs  ⛎️   Ophiuchus\r\n"
printf "  ⛏  vs  ⛏️   Pick\r\n"
printf "  ⛔  vs  ⛔️   No entry\r\n"
printf "  ⛩  vs  ⛩️   Shinto shrine\r\n"
printf "  ⛰  vs  ⛰️   Mountain\r\n"
printf "  ⛱  vs  ⛱️   Umbrella on ground\r\n"
printf "  ⛲  vs  ⛲️   Fountain\r\n"
printf "  ⛳  vs  ⛳️   Flag in hole\r\n"
printf "  ⛵  vs  ⛵️   Sailboat\r\n"
printf "  ⛷  vs  ⛷️   Skier\r\n"
printf "  ⛸  vs  ⛸️   Ice skate\r\n"
printf "  ⛹  vs  ⛹️   Person bouncing ball\r\n"
printf "  ⛺  vs  ⛺️   Tent\r\n"
printf "  ⛽  vs  ⛽️   Fuel pump\r\n"
printf "\r\n"
printf "Alignment check (columns should line up):\r\n"
printf "  |⚠|☀|☁|⚡|⛔|  bare\r\n"
printf "  |⚠️|☀️|☁️|⚡️|⛔️|  with FE0F\r\n"
printf "  |A|B|C|D|E|  ASCII reference\r\n"
