#!/bin/sh
# Box drawing characters
printf "Box drawing test:\r\n"
printf "┌─────────────┐\r\n"
printf "│ Hello World │\r\n"
printf "├─────────────┤\r\n"
printf "│ Test Box    │\r\n"
printf "└─────────────┘\r\n"
printf "\r\n"
printf "Double lines:\r\n"
printf "╔═════════════╗\r\n"
printf "║ Double Box  ║\r\n"
printf "╚═════════════╝\r\n"
printf "\r\n"
printf "Rounded corners:\r\n"
printf "╭─────────────╮\r\n"
printf "│ Rounded Box │\r\n"
printf "╰─────────────╯\r\n"
printf "\r\n"
printf "Heavy lines:\r\n"
printf "┏━━━━━━━━━━━━━┓\r\n"
printf "┃ Heavy Box   ┃\r\n"
printf "┣━━━━━━━━━━━━━┫\r\n"
printf "┃ Thick Lines ┃\r\n"
printf "┗━━━━━━━━━━━━━┛\r\n"
printf "\r\n"
printf "Light and heavy:\r\n"
printf "┌─┬─┐   ┏━┳━┓\r\n"
printf "├─┼─┤   ┣━╋━┫\r\n"
printf "└─┴─┘   ┗━┻━┛\r\n"
