#!/bin/sh
# Box drawing characters
printf "Box drawing test:\r\n"
printf "┌─────────────┐\r\n"
printf "│ Hello World │\r\n"
printf "├─────────────┤\r\n"
printf "│ Test Box    │\r\n"
printf "└─────────────┘\r\n"
printf "\r\n"
printf "Double lines:\r\n"
printf "╔═════════════╗\r\n"
printf "║ Double Box  ║\r\n"
printf "╚═════════════╝\r\n"
printf "\r\n"
printf "Mixed lines:\r\n"
printf "┏━━━━━━━━━━━━━┓\r\n"
printf "┃ Rounded     ┃\r\n"
printf "┣━━━━━━━━━━━━━┫\r\n"
printf "┃ Corners     ┃\r\n"
printf "┗━━━━━━━━━━━━━┛\r\n"
printf "\r\n"
printf "Light and heavy:\r\n"
printf "┌─┬─┐   ┏━┳━┓\r\n"
printf "├─┼─┤   ┣━╋━┫\r\n"
printf "└─┴─┘   ┗━┻━┛\r\n"
