#!/bin/sh
# Special symbols
printf "Mathematical symbols:\r\n"
printf "∑ ∫ ∏ √ ∞ ≈ ≠ ≤ ≥ ± × ÷\r\n"
printf "\r\n"
printf "Currency symbols:\r\n"
printf "$ € £ ¥ ₩ ₽ ₹ ₺\r\n"
printf "\r\n"
printf "Arrow symbols:\r\n"
printf "← ↑ → ↓ ↔ ↕ ↖ ↗ ↘ ↙\r\n"
printf "⇐ ⇑ ⇒ ⇓ ⇔ ⇕ ⇖ ⇗ ⇘ ⇙\r\n"
printf "\r\n"
printf "Miscellaneous symbols:\r\n"
printf "© ® ™ ♠ ♣ ♥ ♦ ♪ ♫ ☀ ☁ ☂ ☃\r\n"
printf "✓ ✗ ✘ ✿ ❀ ❁ ❂ ❃ ❄ ❅ ❆ ❇\r\n"
